config/routes.rb
Urlsh::Application.routes.draw do

  root :to => redirect('/urls/new')
  get 'urls/last' => 'urls#last'

  resources :urls

end

app/models/url.rb
class Url < ActiveRecord::Base
	validates :original, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController

	def index
		@urls = Url.all
	end

	def last
		@url = Url.last
	end

	def show
		@url = Url.where(:random_id => params[:id]).first

		if @url
			redirect_to @url.original
		else
			render "new"
		end
	end

	def new
		@url = Url.new

		letters = [('a'..'z'),('A'..'Z')].map{|t| t.to_a}.flatten
		@url.random_id = (0...8).map{letters[rand(letters.length)]}.join
	end

	def url_params
		params.require(:url).permit(:original, :random_id)
	end

	def create
		@url = Url.create(url_params)

		if @url.save
			redirect_to urls_last_path
		else
			render "new"
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urlcontroller_helper.rb
module UrlcontrollerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Urlsh</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/urls/index.html.erb
<h1> Urls </h1>

<% @urls.each do |url| %>
	<p>
	<%= link_to url.random_id, url_path(:id => url.random_id) %> => <%= url.original %>
	</p>
<% end %>

app/views/urls/last.html.erb
<h1> Urls </h1>

	<p>
	<%= link_to @url.random_id, url_path(:id => @url.random_id) %> => <%= @url.original %>
	</p>

app/views/urls/new.html.erb
<h1> Shorten a URL </h1>

<%= form_for @url do |f| %>
	<p>
		<%= f.label :original %> : <%= f.text_field :original %>

	</p>

	<p>
		<%= f.hidden_field :random_id, :value => @url.random_id %>
		<%= f.submit "Submit my URL" %>

	</p>

<% end %>